task: scierc #re3d
data_dir: 
output_dir: "saved_models"
max_length: 512
max_span_length: 8
span_hidden_size: 150
train_batch_size: 32
eval_batch_size: 16
negative_sample_ratio: 0.01
learning_rate: 1e-4
warmup_proportion: 0.1
num_epoch: 30
eval_per_epoch: 2
debug: False
do_train: True
do_eval: False
train_shuffle: True
model: allenai/scibert_scivocab_uncased #allenai/longformer-base-4096
seed: 1234
context_window: 64
clearml_dataset_project_name: datasets/sci-erc #datasets/re3d
clearml_dataset_name: processed_json #re3d_formatted
clearml_dataset_tags: []
task_tags: ['scierc', 'adam']
gpu: 1
remote: True
early_stopping: True
checkpointing: True
trained_model_path: 
queue: compute
