task: re3d
data_dir: 
output_dir: "saved_models"
max_length: 1024
max_span_length: 8
span_hidden_size: 150
train_batch_size: 8
eval_batch_size: 8
negative_sample_ratio: 0.005
learning_rate: 1e-4
warmup_proportion: 0.1
num_epoch: 10
eval_per_epoch: 5
debug: False
do_train: True
do_eval: True
train_shuffle: True
model: allenai/longformer-base-4096
bert_model_dir: 
seed: 1234
context_window: 64
clearml_dataset_project_name: datasets/re3d
clearml_dataset_name: re3d_formatted
clearml_dataset_tags: []
task_tags: []
gpu: 1
remote: False
early_stopping: False
checkpointing: False
trained_model_path: 
queue: compute
