task: re3d #scierc #scirex #scierc 
data_dir: 
output_dir: "saved_models"
max_length: 512
max_span_length: 8
span_hidden_size: 150
train_batch_size: 8
eval_batch_size: 8
negative_samples_per_batch: 10
learning_rate: 1e-4
warmup_proportion: 0.1
num_epoch: 100
eval_per_epoch: 1
debug: False
do_train: True
do_eval: True
train_shuffle: True
model: allenai/longformer-base-4096 #allenai/scibert_scivocab_uncased 
seed: 1234
clearml_dataset_project_name: datasets/re3d #datasets/sci-erc #datasets/scirex #datasets/sci-erc 
clearml_dataset_name: re3d_formatted #processed_json #scirex-doc #processed_json 
clearml_dataset_tags: []
task_tags: []
gpu: 1
remote: True
early_stopping: True
checkpointing: True
trained_model_path: 
queue: compute
